name: Run Gradle on push

on: [push]

jobs:
  appointment-service-check:
    runs-on: ubuntu-latest
    outputs:
      diff-true: ${{ steps.filter.outputs.appointment-service }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            appointment-service:
              - 'appointment-service/**'
            
  chat-service-check:
    runs-on: ubuntu-latest
    outputs:
      diff-true: ${{ steps.filter.outputs.chat-service }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            chat-service:
              - 'chat-service/**'
            
  user-auth-service-check:
    runs-on: ubuntu-latest
    outputs:
      diff-true: ${{ steps.filter.outputs.user-auth-service }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            user-auth-service:
              - 'user-auth-service/**'

  api-gateway-check:
    runs-on: ubuntu-latest
    outputs:
      diff-true: ${{ steps.filter.outputs.api-gateway }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api-gateway:
              - 'api-gateway/**'

  appointment-microservice-build:
    needs: appointment-service-check
    runs-on: ubuntu-latest
    if: needs.appointment-service-check.outputs.diff-true == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle Build
        working-directory: appointment-service
        run: ./gradlew build

  chat-microservice-build:
    needs: chat-service-check
    runs-on: ubuntu-latest
    if: needs.chat-service-check.outputs.diff-true == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        working-directory: chat-service
        run: ./gradlew build

  user-auth-microservice-build:
    needs: user-auth-service-check
    runs-on: ubuntu-latest
    if: needs.user-auth-service-check.outputs.diff-true == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        working-directory: user-auth-service
        run: ./gradlew build

  api-gateway-build:
    needs: api-gateway-check
    runs-on: ubuntu-latest
    if: needs.api-gateway-check.outputs.diff-true == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        working-directory: api-gateway
        run: ./gradlew build
